AWSTemplateFormatVersion: '2010-09-09'
Description: Stack 4 - Automatizacion (Ibeth-Maicol)

Resources:
  ScaleOut1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !ImportValue ALB-ASG-Luisa-ASG
      ScheduledActionName: ScaleUp1-Luisa
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 4
      StartTime: "2026-06-06T16:20:00Z"

  ScaleOut2:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !ImportValue ALB-ASG-Luisa-ASG
      ScheduledActionName: ScaleUp2-Luisa
      MinSize: 3
      MaxSize: 5
      DesiredCapacity: 5
      StartTime: "2026-06-06T16:25:00Z"

  ScaleIn1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !ImportValue ALB-ASG-Luisa-ASG
      ScheduledActionName: ScaleDown1-Luisa
      MinSize: 1
      MaxSize: 4
      DesiredCapacity: 3
      StartTime: "2026-06-06T16:30:00Z"

  ScaleIn2:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !ImportValue ALB-ASG-Luisa-ASG
      ScheduledActionName: ScaleDown2-Luisa
      MinSize: 1
      MaxSize: 4
      DesiredCapacity: 2
      StartTime: "2026-06-06T16:35:00Z"

Outputs:
  ScaleUp1:
    Description: Accion programada Scale Up 1
    Value: !Ref ScaleOut1

  ScaleUp2:
    Description: Accion programada Scale Up 2
    Value: !Ref ScaleOut2

  ScaleDown1:
    Description: Accion programada Scale Down 1
    Value: !Ref ScaleIn1

  ScaleDown2:
    Description: Accion programada Scale Down 2
    Value: !Ref ScaleIn2